version: "3"

services:
  nodeapp:
    container_name: nodeapp
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: nodeapp:1.0
    ports:
      - "8080:4040"
    networks:
      - my-network

networks:
  my-network:
