version: "3"

services:
  auth-service:
    container_name: auth-service
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    image: auth-service:1.0
    ports:
      - "8080:4040"
    depends_on:
      - auth-sql
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app/src
    networks:
      - my-network

networks:
  my-network:
