version: "3"

services:
  mysql-server-1:
    container_name: mysql-server-1
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: demo
      MYSQL_USER: narayan
      MYSQL_PASSWORD: Narayan@321
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my-network

networks:
  my-network:

volumes:
  mysql_data:
