version: "3"

services:
  mysql-server-1:
    container_name: mysql-server-1
    image: mysql:latest
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my-network

networks:
  my-network:

volumes:
  mysql_data:
