version: "3"

services:
  auth-service:
    container_name: auth-service
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: auth-service:1.0
    env_file:
      - .env
    ports:
      - "8080:4040"
    networks:
      - my-network

networks:
  my-network:
